# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{app_frame}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Mateo Murphy"]
  s.date = %q{2011-02-12}
  s.description = %q{TODO: longer description of your gem}
  s.email = %q{mateo.murphy@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "app/views/app_frame/actions/_form.html.haml",
    "app/views/app_frame/actions/edit.html.haml",
    "app/views/app_frame/actions/index.html.haml",
    "app/views/app_frame/actions/new.html.haml",
    "app/views/app_frame/actions/show.html.haml",
    "app/views/app_frame/layout/_head.html.haml",
    "app/views/layouts/app_frame/default.html.haml",
    "app/views/layouts/web_app_theme/default.html.haml",
    "app/views/web_app_theme/actions/_form.html.haml",
    "app/views/web_app_theme/actions/_list.html.haml",
    "app/views/web_app_theme/actions/_show.html.haml",
    "app/views/web_app_theme/actions/_sidebar.html.haml",
    "app/views/web_app_theme/actions/edit.html.haml",
    "app/views/web_app_theme/actions/index.html.haml",
    "app/views/web_app_theme/actions/new.html.haml",
    "app/views/web_app_theme/actions/show.html.haml",
    "app_frame.gemspec",
    "lib/app_frame.rb",
    "lib/app_frame/controller_methods.rb",
    "lib/app_frame/fallback_resolver.rb",
    "lib/app_frame/view_methods.rb",
    "lib/engine.rb",
    "lib/table_for.rb",
    "lib/table_for/action.rb",
    "lib/table_for/attribute.rb",
    "lib/table_for/builder.rb",
    "lib/table_for/column.rb",
    "lib/table_for/helper.rb",
    "public/javascripts/app_frame/application.js",
    "public/stylesheets/app_frame/application.css",
    "test/helper.rb",
    "test/test_app_frame.rb"
  ]
  s.homepage = %q{http://github.com/mateomurphy/app_frame}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{TODO: one-line summary of your gem}
  s.test_files = [
    "test/helper.rb",
    "test/test_app_frame.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<haml>, [">= 0"])
      s.add_runtime_dependency(%q<haml>, ["> 0.1"])
      s.add_runtime_dependency(%q<inherited_resources>, ["> 0.1"])
      s.add_runtime_dependency(%q<simple_form>, ["> 0.1"])
      s.add_runtime_dependency(%q<show_for>, ["> 0.1"])
      s.add_runtime_dependency(%q<will_paginate>, ["> 0.1"])
      s.add_runtime_dependency(%q<simple-navigation>, ["> 0.1"])
    else
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<haml>, [">= 0"])
      s.add_dependency(%q<haml>, ["> 0.1"])
      s.add_dependency(%q<inherited_resources>, ["> 0.1"])
      s.add_dependency(%q<simple_form>, ["> 0.1"])
      s.add_dependency(%q<show_for>, ["> 0.1"])
      s.add_dependency(%q<will_paginate>, ["> 0.1"])
      s.add_dependency(%q<simple-navigation>, ["> 0.1"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<haml>, [">= 0"])
    s.add_dependency(%q<haml>, ["> 0.1"])
    s.add_dependency(%q<inherited_resources>, ["> 0.1"])
    s.add_dependency(%q<simple_form>, ["> 0.1"])
    s.add_dependency(%q<show_for>, ["> 0.1"])
    s.add_dependency(%q<will_paginate>, ["> 0.1"])
    s.add_dependency(%q<simple-navigation>, ["> 0.1"])
  end
end

